#!/usr/bin/env bash
# Regenerate client/src/generated/ from the Ermine declarations.
#
#   client/scripts/generate.sh [<output dir>]
#
# One zod module per exported type, written by `bin/ermine-schema --zod`, plus an
# index.ts that re-exports them under stable names and a registry of
# widget name -> props schema.  Nothing here is edited by hand;
# scripts/check-generated.sh regenerates into a temp dir and diffs (design note
# section 3.5's equality check).
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
client="$(dirname "$here")"
repo="$(dirname "$client")"
out="${1:-$client/src/generated}"

# module:Type:file-stem:exported-name
types=(
  "Layout.Doc:Node:doc:DocNodeSchema"
  "Layout.Widgets.Format:CellFormat:cellFormat:CellFormatSchema"
  "Layout.Widgets.Table:TableProps:table:TablePropsSchema"
  "Layout.Widgets.Drilldown:DrilldownTableProps:drilldown:DrilldownTablePropsSchema"
  "Layout.Widgets.Scorecard:ScorecardProps:scorecard:ScorecardPropsSchema"
)

mkdir -p "$out"
for spec in "${types[@]}"; do
  IFS=: read -r mod ty stem _name <<< "$spec"
  "$repo/bin/ermine-schema" --zod -i "$mod" "$ty" > "$out/$stem.ts"
  # ermine-schema prints without a trailing newline; keep the files newline-terminated
  [ -n "$(tail -c 1 "$out/$stem.ts")" ] && printf '\n' >> "$out/$stem.ts"
done

{
  echo "// Generated by client/scripts/generate.sh -- do not edit."
  echo "// Regenerate after changing core/src/main/resources/modules/Layout/Widgets/*.e"
  echo "// or Layout/Doc.e; scripts/check-generated.sh fails the build if this is stale."
  echo
  echo 'import { z } from "zod";'
  for spec in "${types[@]}"; do
    IFS=: read -r _mod _ty stem name <<< "$spec"
    echo "import { Schema as ${name}Raw } from \"./$stem\";"
  done
  echo
  for spec in "${types[@]}"; do
    IFS=: read -r mod ty stem name <<< "$spec"
    echo "/** $mod.$ty */"
    echo "export const $name: z.ZodTypeAny = ${name}Raw;"
  done
  echo
  echo "/** Widget registry name -> the zod its props are validated with. */"
  echo "export const WIDGET_PROP_SCHEMAS: Record<string, z.ZodTypeAny> = {"
  echo "  table: TablePropsSchema,"
  echo "  drilldownTable: DrilldownTablePropsSchema,"
  echo "  scorecard: ScorecardPropsSchema,"
  echo "};"
} > "$out/index.ts"

echo "generated ${#types[@]} zod modules + index.ts in $out"
