package com.clarifi.reporting
package backends

import java.io.{Writer, StringWriter}
import java.sql.{DatabaseMetaData => DM, ResultSet}

import scalaz.IterV
import scalaz.std.function._
import scalaz.std.list._
import scalaz.std.string._
import scalaz.syntax.functor._
import scalaz.syntax.semigroup._
import scalaz.syntax.std.list._
import scalaz.syntax.std.all.ToTuple2Ops

import scalaparsers.{Document => PP}
import ermine.parsing.inverseStringLiteral
import ermine.session.{Lib => ELib, Session}
import ermine.session.Session.SourceFile
import ermine.syntax.Explicit
import ermine.Global

import sql.{ SqlColumn, SqlEmitter }

/** Inspecting a JDBC database. */
object SqlMetadata {
  type Schemata = Map[TableName, Header]
  type ColumnInfo = (TableName, (SqlColumn, PrimT))

  private def decodeNullable(x: Int): Boolean = x match {
    case DM.columnNoNulls => false
    case DM.columnNullable | DM.columnNullableUnknown | _ => true
  }

  private def decodeType(dt: Int, typeName: String, colSize: Int,
                         nullable: Boolean, emit: SqlEmitter): Option[PrimT] =
    emit sqlPrimT (dt, typeName, colSize) map {nn => if (nullable) nn.withNull else nn}

  /** Extract schema info from a DatabaseMetaData#getColumns call at
    * its current row. */
  private def readSchemaInfo(rs: ResultSet, emit: SqlEmitter): Option[ColumnInfo] = for {
    ty <- decodeType(rs getInt "DATA_TYPE",
                    rs getString "TYPE_NAME",
                    rs getInt "COLUMN_SIZE",
                    decodeNullable(rs getInt "NULLABLE"),
                    emit)
  } yield (TableName(rs getString "TABLE_NAME",
                     Option(rs getString "TABLE_SCHEM") toList), // yes, SCHEM, not SCHEME
           (rs getString "COLUMN_NAME", ty))

  private def deriveSchemata(cols: Traversable[ColumnInfo]): Schemata =
    cols groupBy (_._1) mapValues (_.view map (_._2) toMap)

  private def columnMetaData(catalog: Option[String],
                             schemaPattern: Option[String],
                             tableNamePat: String, colPat: String,
                             emit: SqlEmitter
                           ): DB[Traversable[ColumnInfo]] =
    DB.bracket[ResultSet, Traversable[ColumnInfo]](
      _.getMetaData.getColumns(catalog orNull, schemaPattern orNull, tableNamePat, colPat),
      DB.closeResultSet,
      colRs => DB.enumResultSet(colRs, IterV.collect[Option[ColumnInfo], Vector],
                               // XXX don't be so cavalier about
                               // throwing away columns
                               readSchemaInfo(_, emit)) map (_.run.flatten))

  /** Look up schemata in a database.
   *
   * @param emit A SqlEmitter that knows how to decode JDBC types.
   * @param catalog table catalog, or None for all catalogs
   * @param schemaPattern SQL schema name pattern or None for all schemata
   * @param tableNamePat A pattern string for table names to find.
   * @param colPat A pattern string for column names to find.
   * @returns table and column presence/type listings */
  def schemata(emit: SqlEmitter, catalog: Option[String] = None,
               schemaPattern: Option[String] = None,
               tableNamePat: String = "%", colPat: String = "%"
             ): DB[Schemata] =
    (columnMetaData(catalog, schemaPattern, tableNamePat, colPat, emit)
     map deriveSchemata)
}

/** Ermine code and modules generated by inspecting a database. */
object SqlErmine {
  import SqlMetadata.Schemata

  sealed trait ErmineGen {
    def ermineCode: PP
  }

  private val usualModules: Map[String, (Option[String], List[Explicit[Global]], Boolean)] =
    (ELib.primBindings.map(_._1.module).toSet[String]
     zip (Stream continually ((None, List.empty, false))) toMap)

  private def erminePrim(t: PrimT): PP = {
    val base = (ELib.primBindings find (_._2.getClass == t.getClass)
                map (_._1.string)
                getOrElse (sys error ("No Ermine PrimT for %s" format t)))
    if (t.nullable) "Nullable" :+: (base: PP) else base
  }

  case class Comment(text: String) extends ErmineGen {
    def ermineCode = PP.vsep(text.split("""[\r\n]""").view
                             map (line => PP.text("-- " |+| line)) toList)
  }

  case class ModuleHead(name: String,
                        imports: Map[String, (Option[String], List[Explicit[Global]], Boolean)])
       extends ErmineGen {
    def ermineCode = "module" :+: name :+: PP.text("where") above
       PP.vsep(imports.view map {case (modname, (as, explicits, usingp)) =>
                 // TODO SMRC as, explicits, usingp
                 "import" :+: PP.text(modname)
               } toList)
  }

  case class FieldDecl(name: String, typ: PrimT) extends ErmineGen {
    def ermineCode = "field" :+: name :+: ":" :+: erminePrim(typ)
  }

  case class TableDecl(schema: List[String], name: String,
                       fields: List[FieldDecl]) extends ErmineGen {
    def ermineCode = "table" :+: (schema :+ name mkString ".") :+: ":" :+:
      PP.nest(2, "[" :: PP.hsep(fields map (fld => PP.text(fld.name))
                               intersperse PP.text(","))
              :: PP.text("]"))
  }

  case class DatabaseBlock(name: String, body: List[(Comment, TableDecl)])
       extends ErmineGen {
    def ermineCode = "database" :+: (inverseStringLiteral(name): PP) above
      PP.nest(2, PP.vsep(body.view flatMap
                         (_ fold ((c, t) => List(c.ermineCode, t.ermineCode)))
                         toList))
  }

  case class Module(head: ModuleHead, fields: Set[FieldDecl],
                    tables: DatabaseBlock) extends ErmineGen {
    def ermineCode = (head.ermineCode
                      above PP.vsep(fields.toList sortBy (_.name) map (_.ermineCode))
                      above tables.ermineCode
                      above Comment(head.name |+| " ends here").ermineCode)
  }

  /** Build a module based on discovered database schemata.
    *
    * @param moduleName The Ermine module name.
    * @param database Name of the `database` block.
    * @param scm Schemata read from, say `SqlMetadata.schemata`. */
  def databaseModule(moduleName: String, database: String,
                     scm: Schemata): Module = {
    val fieldDecl = Function tupled FieldDecl
    Module(ModuleHead(moduleName, usualModules),
           scm.view flatMap (_._2 map fieldDecl) toSet,
           DatabaseBlock(database, scm.view map {case (TableName(dname, dscm, _), cs) =>
             (Comment("generated for " |+| dname),
              TableDecl(dscm, dname, cs map fieldDecl toList))} toList))
  }

  private def written[A](f: StringWriter => A): (String, A) = {
    val w = new StringWriter
    val a = f(w)
    (w toString, a)
  }

  /** A dynamic loader of independent modules of fields and tables.
    *
    * For the loader `modules("Hi", Map("Things" -> ("bits",
    * _somedb_)))`, doing "import Hi.Things" builds a module with a
    * `database "bits"` block containing all tables in _somedb_, and
    * declarations for all fields in said tables.
    *
    * @param prefix implicit namespace of this loader
    * @param databases submodules of `prefix`, mapped to database
    *        block names and DB action executors.
    */
  def modules(prefix: String,
              databases: PartialFunction[String, (String, DB[Schemata], Run[DB])]
            ): SourceFile.Loader = {
    val modNamePref = prefix |+| "."
    reqMod => for {
      tail <- if (reqMod startsWith modNamePref)
        Some(reqMod drop modNamePref.size) else None
      db <- databases.lift(tail)
      (dbName, schemata, runner) = db
      module = databaseModule(reqMod, dbName, runner run schemata)
    } yield Session.Literal(written(module.ermineCode
                                    format (java.lang.Integer.MAX_VALUE, _))._1,
                            reqMod)
  }
}
