-- GENERATED by data/schema/build-sales-schema.mjs -- do not edit; edit the generator and rerun.
-- ErmineSales schema, T-SQL (SQL Server 2022) variant (tracker/db/SCHEMA-SALES.md; contract data/schema/sales.contract.json).
-- Idempotent: drops every view, then every table (facts before dims, for the FKs), then creates.

-- Dialect differences from the twin file (and ONLY these):
--   D-1 names: MSSQL objects live in dbo and are written dbo.x; SQLite has no schemas
--       (a qualified name means an ATTACHed database), so objects are bare in main.
--   D-2 Date: MSSQL date; SQLite INTEGER holding epoch milliseconds at 00:00 GMT,
--       because SqliteEmitter writes a Date literal as d.getTime (SqlEmitter.scala:696)
--       and its own temp-table DDL types Date as integer (:724).
--   D-3 String: MSSQL nvarchar(n) (the length is the contract's maxLength); SQLite TEXT.
--       Double: float vs REAL. Int: int vs INTEGER. SQLite tables are STRICT so a
--       wrongly typed CSV value fails the load instead of being stored as text.
--   D-4 batches: CREATE VIEW must start a T-SQL batch, hence GO (sqlcmd); SQLite needs none.
--   D-5 indexes: MSSQL ix_fol_region_date INCLUDEs the summed columns; SQLite has no INCLUDE.
--   D-6 FKs: enforced by MSSQL always; by SQLite only under PRAGMA foreign_keys = ON,
--       which this file sets for its own connection (loaders must set it too).
--   D-7 guard: the MSSQL file refuses to run in a system database; SQLite has none.
--   D-8 quoting: T-SQL column names are [bracketed] (lineNo is the reserved LINENO); SQLite bare.

SET NOCOUNT ON;
IF DB_NAME() IN (N'master', N'model', N'msdb', N'tempdb')
  THROW 50001, N'sales.mssql.sql: connect to the domain database (ErmineSales), not a system database', 1;
GO

DROP VIEW IF EXISTS dbo.calendar;
DROP VIEW IF EXISTS dbo.targets;
DROP VIEW IF EXISTS dbo.sales_items;
DROP VIEW IF EXISTS dbo.sales;
DROP TABLE IF EXISTS dbo.sales_report;
DROP TABLE IF EXISTS dbo.fact_target;
DROP TABLE IF EXISTS dbo.fact_order_line;
DROP TABLE IF EXISTS dbo.dim_date;
DROP TABLE IF EXISTS dbo.dim_customer;
DROP TABLE IF EXISTS dbo.dim_rep;
DROP TABLE IF EXISTS dbo.dim_channel;
DROP TABLE IF EXISTS dbo.dim_product;
DROP TABLE IF EXISTS dbo.dim_region;
GO

-- One row per sales region. regionCode is the Ermine `region` value every view exposes.
CREATE TABLE dbo.dim_region (
  [regionId] int NOT NULL,
  [regionCode] nvarchar(40) NOT NULL,
  [regionName] nvarchar(80) NOT NULL,
  [regionGroup] nvarchar(8) NOT NULL,
  [countryName] nvarchar(80) NOT NULL,
  [countryCode] nvarchar(2) NOT NULL,
  [populationWeight] float NOT NULL,
  CONSTRAINT pk_dim_region PRIMARY KEY ([regionId]),
  CONSTRAINT uq_dim_region_regionCode UNIQUE ([regionCode])
);

-- The catalogue. productName is the Ermine `item` value (Sales.e).
CREATE TABLE dbo.dim_product (
  [productId] int NOT NULL,
  [sku] nvarchar(20) NOT NULL,
  [productName] nvarchar(80) NOT NULL,
  [category] nvarchar(40) NOT NULL,
  [subCategory] nvarchar(40) NOT NULL,
  [priceBand] nvarchar(10) NOT NULL,
  [listPrice] float NOT NULL,
  [unitCost] float NOT NULL,
  CONSTRAINT pk_dim_product PRIMARY KEY ([productId]),
  CONSTRAINT uq_dim_product_sku UNIQUE ([sku]),
  CONSTRAINT uq_dim_product_productName UNIQUE ([productName])
);

-- Sales channel (Ai/SalesByRegion.e channel dimension). isDirect is a Y/N String: the corpus has 0 Bool columns (SURVEY-CORPUS §5).
CREATE TABLE dbo.dim_channel (
  [channelId] int NOT NULL,
  [channelName] nvarchar(40) NOT NULL,
  [isDirect] nvarchar(1) NOT NULL,
  CONSTRAINT pk_dim_channel PRIMARY KEY ([channelId]),
  CONSTRAINT uq_dim_channel_channelName UNIQUE ([channelName])
);

-- Sales reps; each belongs to one region. repScore is the one Nullable Int (Present/SalesDashboard.e repScore).
CREATE TABLE dbo.dim_rep (
  [repId] int NOT NULL,
  [repName] nvarchar(80) NOT NULL,
  [regionId] int NOT NULL,
  [repTeam] nvarchar(40) NOT NULL,
  [hireDate] date NOT NULL,
  [repScore] int NULL,
  CONSTRAINT pk_dim_rep PRIMARY KEY ([repId]),
  CONSTRAINT fk_dim_rep_regionId FOREIGN KEY ([regionId]) REFERENCES dbo.dim_region ([regionId])
);

-- Customers; each belongs to one region (Algebra/OrderLedger.e customerDim, complete here: FKs are enforced).
CREATE TABLE dbo.dim_customer (
  [customerId] int NOT NULL,
  [customerName] nvarchar(120) NOT NULL,
  [customerTier] nvarchar(10) NOT NULL,
  [regionId] int NOT NULL,
  [signupDate] date NOT NULL,
  CONSTRAINT pk_dim_customer PRIMARY KEY ([customerId]),
  CONSTRAINT fk_dim_customer_regionId FOREIGN KEY ([regionId]) REFERENCES dbo.dim_region ([regionId])
);

-- The calendar. xs = exactly the 8 sale days (so the `calendar` view equals FetchCrosstab.e's literal); s+ = every day of the tier range. monthName is FetchCrosstab's "YYYY-MM" key.
CREATE TABLE dbo.dim_date (
  [day] date NOT NULL,
  [yearNo] int NOT NULL,
  [quarterNo] int NOT NULL,
  [monthNo] int NOT NULL,
  [monthName] nvarchar(7) NOT NULL,
  [quarterName] nvarchar(7) NOT NULL,
  [weekdayNo] int NOT NULL,
  [weekdayName] nvarchar(9) NOT NULL,
  CONSTRAINT pk_dim_date PRIMARY KEY ([day])
);

-- One row per order line. lineAmount is the Ermine `amount`, quantity the Ermine `units`, both summed by the views.
CREATE TABLE dbo.fact_order_line (
  [orderId] int NOT NULL,
  [lineNo] int NOT NULL,
  [orderDate] date NOT NULL,
  [regionId] int NOT NULL,
  [customerId] int NOT NULL,
  [productId] int NOT NULL,
  [repId] int NOT NULL,
  [channelId] int NOT NULL,
  [quantity] int NOT NULL,
  [unitPrice] float NOT NULL,
  [discountPct] float NOT NULL,
  [lineAmount] float NOT NULL,
  [promoCode] nvarchar(20) NULL,
  CONSTRAINT pk_fact_order_line PRIMARY KEY ([orderId], [lineNo]),
  CONSTRAINT fk_fact_order_line_orderDate FOREIGN KEY ([orderDate]) REFERENCES dbo.dim_date ([day]),
  CONSTRAINT fk_fact_order_line_regionId FOREIGN KEY ([regionId]) REFERENCES dbo.dim_region ([regionId]),
  CONSTRAINT fk_fact_order_line_customerId FOREIGN KEY ([customerId]) REFERENCES dbo.dim_customer ([customerId]),
  CONSTRAINT fk_fact_order_line_productId FOREIGN KEY ([productId]) REFERENCES dbo.dim_product ([productId]),
  CONSTRAINT fk_fact_order_line_repId FOREIGN KEY ([repId]) REFERENCES dbo.dim_rep ([repId]),
  CONSTRAINT fk_fact_order_line_channelId FOREIGN KEY ([channelId]) REFERENCES dbo.dim_channel ([channelId])
);

-- A sales target per region per quarter; the `targets` view sums them per region.
CREATE TABLE dbo.fact_target (
  [regionId] int NOT NULL,
  [yearNo] int NOT NULL,
  [quarterNo] int NOT NULL,
  [targetAmount] float NOT NULL,
  CONSTRAINT pk_fact_target PRIMARY KEY ([regionId], [yearNo], [quarterNo]),
  CONSTRAINT fk_fact_target_regionId FOREIGN KEY ([regionId]) REFERENCES dbo.dim_region ([regionId])
);

-- Backs Doc/SalesReport.e (sales : [srRegion, srSales, srDelta]). A BASE TABLE (a mart snapshot) at every tier: its xs values are literals no view over the 8 sales can derive.
CREATE TABLE dbo.sales_report (
  [srRegion] nvarchar(8) NOT NULL,
  [srSales] float NOT NULL,
  [srDelta] float NOT NULL,
  CONSTRAINT pk_sales_report PRIMARY KEY ([srRegion])
);

CREATE INDEX ix_fol_region_date ON dbo.fact_order_line ([regionId], [orderDate]) INCLUDE ([lineAmount], [quantity], [productId]);
CREATE INDEX ix_fol_date ON dbo.fact_order_line ([orderDate]);
CREATE INDEX ix_fol_product ON dbo.fact_order_line ([productId]);
CREATE INDEX ix_rep_region ON dbo.dim_rep ([regionId]);
CREATE INDEX ix_customer_region ON dbo.dim_customer ([regionId]);
GO

-- backs FetchData.e:20 `sales : [region, day, amount, units]`; key (region, day)
CREATE VIEW dbo.sales AS
SELECT r.regionCode AS region, f.orderDate AS day,
       SUM(f.lineAmount) AS amount, SUM(f.quantity) AS units
FROM dbo.fact_order_line AS f
JOIN dbo.dim_region AS r ON r.regionId = f.regionId
GROUP BY r.regionCode, f.orderDate;
GO

-- backs Sales.e:71-75 the Sale record (region, day, amount, units, item); key (region, day, item)
CREATE VIEW dbo.sales_items AS
SELECT r.regionCode AS region, f.orderDate AS day, p.productName AS item,
       SUM(f.lineAmount) AS amount, SUM(f.quantity) AS units
FROM dbo.fact_order_line AS f
JOIN dbo.dim_region AS r ON r.regionId = f.regionId
JOIN dbo.dim_product AS p ON p.productId = f.productId
GROUP BY r.regionCode, f.orderDate, p.productName;
GO

-- backs FetchData.e:33 `targets : [region, target]`; key (region)
CREATE VIEW dbo.targets AS
SELECT r.regionCode AS region, SUM(t.targetAmount) AS target
FROM dbo.fact_target AS t
JOIN dbo.dim_region AS r ON r.regionId = t.regionId
GROUP BY r.regionCode;
GO

-- backs FetchCrosstab.e `calendar : [day, monthName]` (a module-local literal today); key (day)
CREATE VIEW dbo.calendar AS
SELECT d.day AS day, d.monthName AS monthName
FROM dbo.dim_date AS d;
GO
