-- GENERATED by data/schema/build-sales-schema.mjs -- do not edit; edit the generator and rerun.
-- ErmineSales schema, SQLite (3.37+, STRICT tables) variant (tracker/db/SCHEMA-SALES.md; contract data/schema/sales.contract.json).
-- Idempotent: drops every view, then every table (facts before dims, for the FKs), then creates.

-- Dialect differences from the twin file (and ONLY these):
--   D-1 names: MSSQL objects live in dbo and are written dbo.x; SQLite has no schemas
--       (a qualified name means an ATTACHed database), so objects are bare in main.
--   D-2 Date: MSSQL date; SQLite INTEGER holding epoch milliseconds at 00:00 GMT,
--       because SqliteEmitter writes a Date literal as d.getTime (SqlEmitter.scala:696)
--       and its own temp-table DDL types Date as integer (:724).
--   D-3 String: MSSQL nvarchar(n) (the length is the contract's maxLength); SQLite TEXT.
--       Double: float vs REAL. Int: int vs INTEGER. SQLite tables are STRICT so a
--       wrongly typed CSV value fails the load instead of being stored as text.
--   D-4 batches: CREATE VIEW must start a T-SQL batch, hence GO (sqlcmd); SQLite needs none.
--   D-5 indexes: MSSQL ix_fol_region_date INCLUDEs the summed columns; SQLite has no INCLUDE.
--   D-6 FKs: enforced by MSSQL always; by SQLite only under PRAGMA foreign_keys = ON,
--       which this file sets for its own connection (loaders must set it too).
--   D-7 guard: the MSSQL file refuses to run in a system database; SQLite has none.
--   D-8 quoting: T-SQL column names are [bracketed] (lineNo is the reserved LINENO); SQLite bare.

PRAGMA foreign_keys = ON;

DROP VIEW IF EXISTS calendar;
DROP VIEW IF EXISTS targets;
DROP VIEW IF EXISTS sales_items;
DROP VIEW IF EXISTS sales;
DROP TABLE IF EXISTS sales_report;
DROP TABLE IF EXISTS fact_target;
DROP TABLE IF EXISTS fact_order_line;
DROP TABLE IF EXISTS dim_date;
DROP TABLE IF EXISTS dim_customer;
DROP TABLE IF EXISTS dim_rep;
DROP TABLE IF EXISTS dim_channel;
DROP TABLE IF EXISTS dim_product;
DROP TABLE IF EXISTS dim_region;

-- One row per sales region. regionCode is the Ermine `region` value every view exposes.
CREATE TABLE dim_region (
  regionId INTEGER NOT NULL,
  regionCode TEXT NOT NULL,
  regionName TEXT NOT NULL,
  regionGroup TEXT NOT NULL,
  countryName TEXT NOT NULL,
  countryCode TEXT NOT NULL,
  populationWeight REAL NOT NULL,
  CONSTRAINT pk_dim_region PRIMARY KEY (regionId),
  CONSTRAINT uq_dim_region_regionCode UNIQUE (regionCode)
) STRICT;

-- The catalogue. productName is the Ermine `item` value (Sales.e).
CREATE TABLE dim_product (
  productId INTEGER NOT NULL,
  sku TEXT NOT NULL,
  productName TEXT NOT NULL,
  category TEXT NOT NULL,
  subCategory TEXT NOT NULL,
  priceBand TEXT NOT NULL,
  listPrice REAL NOT NULL,
  unitCost REAL NOT NULL,
  CONSTRAINT pk_dim_product PRIMARY KEY (productId),
  CONSTRAINT uq_dim_product_sku UNIQUE (sku),
  CONSTRAINT uq_dim_product_productName UNIQUE (productName)
) STRICT;

-- Sales channel (Ai/SalesByRegion.e channel dimension). isDirect is a Y/N String: the corpus has 0 Bool columns (SURVEY-CORPUS §5).
CREATE TABLE dim_channel (
  channelId INTEGER NOT NULL,
  channelName TEXT NOT NULL,
  isDirect TEXT NOT NULL,
  CONSTRAINT pk_dim_channel PRIMARY KEY (channelId),
  CONSTRAINT uq_dim_channel_channelName UNIQUE (channelName)
) STRICT;

-- Sales reps; each belongs to one region. repScore is the one Nullable Int (Present/SalesDashboard.e repScore).
CREATE TABLE dim_rep (
  repId INTEGER NOT NULL,
  repName TEXT NOT NULL,
  regionId INTEGER NOT NULL,
  repTeam TEXT NOT NULL,
  hireDate INTEGER NOT NULL,
  repScore INTEGER NULL,
  CONSTRAINT pk_dim_rep PRIMARY KEY (repId),
  CONSTRAINT fk_dim_rep_regionId FOREIGN KEY (regionId) REFERENCES dim_region (regionId)
) STRICT;

-- Customers; each belongs to one region (Algebra/OrderLedger.e customerDim, complete here: FKs are enforced).
CREATE TABLE dim_customer (
  customerId INTEGER NOT NULL,
  customerName TEXT NOT NULL,
  customerTier TEXT NOT NULL,
  regionId INTEGER NOT NULL,
  signupDate INTEGER NOT NULL,
  CONSTRAINT pk_dim_customer PRIMARY KEY (customerId),
  CONSTRAINT fk_dim_customer_regionId FOREIGN KEY (regionId) REFERENCES dim_region (regionId)
) STRICT;

-- The calendar. xs = exactly the 8 sale days (so the `calendar` view equals FetchCrosstab.e's literal); s+ = every day of the tier range. monthName is FetchCrosstab's "YYYY-MM" key.
CREATE TABLE dim_date (
  day INTEGER NOT NULL,
  yearNo INTEGER NOT NULL,
  quarterNo INTEGER NOT NULL,
  monthNo INTEGER NOT NULL,
  monthName TEXT NOT NULL,
  quarterName TEXT NOT NULL,
  weekdayNo INTEGER NOT NULL,
  weekdayName TEXT NOT NULL,
  CONSTRAINT pk_dim_date PRIMARY KEY (day)
) STRICT;

-- One row per order line. lineAmount is the Ermine `amount`, quantity the Ermine `units`, both summed by the views.
CREATE TABLE fact_order_line (
  orderId INTEGER NOT NULL,
  lineNo INTEGER NOT NULL,
  orderDate INTEGER NOT NULL,
  regionId INTEGER NOT NULL,
  customerId INTEGER NOT NULL,
  productId INTEGER NOT NULL,
  repId INTEGER NOT NULL,
  channelId INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  unitPrice REAL NOT NULL,
  discountPct REAL NOT NULL,
  lineAmount REAL NOT NULL,
  promoCode TEXT NULL,
  CONSTRAINT pk_fact_order_line PRIMARY KEY (orderId, lineNo),
  CONSTRAINT fk_fact_order_line_orderDate FOREIGN KEY (orderDate) REFERENCES dim_date (day),
  CONSTRAINT fk_fact_order_line_regionId FOREIGN KEY (regionId) REFERENCES dim_region (regionId),
  CONSTRAINT fk_fact_order_line_customerId FOREIGN KEY (customerId) REFERENCES dim_customer (customerId),
  CONSTRAINT fk_fact_order_line_productId FOREIGN KEY (productId) REFERENCES dim_product (productId),
  CONSTRAINT fk_fact_order_line_repId FOREIGN KEY (repId) REFERENCES dim_rep (repId),
  CONSTRAINT fk_fact_order_line_channelId FOREIGN KEY (channelId) REFERENCES dim_channel (channelId)
) STRICT;

-- A sales target per region per quarter; the `targets` view sums them per region.
CREATE TABLE fact_target (
  regionId INTEGER NOT NULL,
  yearNo INTEGER NOT NULL,
  quarterNo INTEGER NOT NULL,
  targetAmount REAL NOT NULL,
  CONSTRAINT pk_fact_target PRIMARY KEY (regionId, yearNo, quarterNo),
  CONSTRAINT fk_fact_target_regionId FOREIGN KEY (regionId) REFERENCES dim_region (regionId)
) STRICT;

-- Backs Doc/SalesReport.e (sales : [srRegion, srSales, srDelta]). A BASE TABLE (a mart snapshot) at every tier: its xs values are literals no view over the 8 sales can derive.
CREATE TABLE sales_report (
  srRegion TEXT NOT NULL,
  srSales REAL NOT NULL,
  srDelta REAL NOT NULL,
  CONSTRAINT pk_sales_report PRIMARY KEY (srRegion)
) STRICT;

CREATE INDEX ix_fol_region_date ON fact_order_line (regionId, orderDate);
CREATE INDEX ix_fol_date ON fact_order_line (orderDate);
CREATE INDEX ix_fol_product ON fact_order_line (productId);
CREATE INDEX ix_rep_region ON dim_rep (regionId);
CREATE INDEX ix_customer_region ON dim_customer (regionId);

-- backs FetchData.e:20 `sales : [region, day, amount, units]`; key (region, day)
CREATE VIEW sales AS
SELECT r.regionCode AS region, f.orderDate AS day,
       SUM(f.lineAmount) AS amount, SUM(f.quantity) AS units
FROM fact_order_line AS f
JOIN dim_region AS r ON r.regionId = f.regionId
GROUP BY r.regionCode, f.orderDate;

-- backs Sales.e:71-75 the Sale record (region, day, amount, units, item); key (region, day, item)
CREATE VIEW sales_items AS
SELECT r.regionCode AS region, f.orderDate AS day, p.productName AS item,
       SUM(f.lineAmount) AS amount, SUM(f.quantity) AS units
FROM fact_order_line AS f
JOIN dim_region AS r ON r.regionId = f.regionId
JOIN dim_product AS p ON p.productId = f.productId
GROUP BY r.regionCode, f.orderDate, p.productName;

-- backs FetchData.e:33 `targets : [region, target]`; key (region)
CREATE VIEW targets AS
SELECT r.regionCode AS region, SUM(t.targetAmount) AS target
FROM fact_target AS t
JOIN dim_region AS r ON r.regionId = t.regionId
GROUP BY r.regionCode;

-- backs FetchCrosstab.e `calendar : [day, monthName]` (a module-local literal today); key (day)
CREATE VIEW calendar AS
SELECT d.day AS day, d.monthName AS monthName
FROM dim_date AS d;
