-- GENERATED by data/schema/build-sales-schema.mjs -- do not edit.
-- ErmineSales smoke, sqlite. Prints k|v lines; at tier xs the output must equal
-- data/schema/sales.smoke.expected-xs.txt byte for byte.
-- Run: node data/schema/verify-sqlite.mjs (or any SQLite shell with | as the separator)
SELECT k, v FROM (
SELECT 1 AS n, 'count.dim_region' AS k, CAST((SELECT COUNT(*) FROM dim_region) AS TEXT) AS v
UNION ALL SELECT 2 AS n, 'count.dim_product' AS k, CAST((SELECT COUNT(*) FROM dim_product) AS TEXT) AS v
UNION ALL SELECT 3 AS n, 'count.dim_channel' AS k, CAST((SELECT COUNT(*) FROM dim_channel) AS TEXT) AS v
UNION ALL SELECT 4 AS n, 'count.dim_rep' AS k, CAST((SELECT COUNT(*) FROM dim_rep) AS TEXT) AS v
UNION ALL SELECT 5 AS n, 'count.dim_customer' AS k, CAST((SELECT COUNT(*) FROM dim_customer) AS TEXT) AS v
UNION ALL SELECT 6 AS n, 'count.dim_date' AS k, CAST((SELECT COUNT(*) FROM dim_date) AS TEXT) AS v
UNION ALL SELECT 7 AS n, 'count.fact_order_line' AS k, CAST((SELECT COUNT(*) FROM fact_order_line) AS TEXT) AS v
UNION ALL SELECT 8 AS n, 'count.fact_target' AS k, CAST((SELECT COUNT(*) FROM fact_target) AS TEXT) AS v
UNION ALL SELECT 9 AS n, 'count.sales_report' AS k, CAST((SELECT COUNT(*) FROM sales_report) AS TEXT) AS v
UNION ALL SELECT 10 AS n, 'count.sales' AS k, CAST((SELECT COUNT(*) FROM sales) AS TEXT) AS v
UNION ALL SELECT 11 AS n, 'count.sales_items' AS k, CAST((SELECT COUNT(*) FROM sales_items) AS TEXT) AS v
UNION ALL SELECT 12 AS n, 'count.targets' AS k, CAST((SELECT COUNT(*) FROM targets) AS TEXT) AS v
UNION ALL SELECT 13 AS n, 'count.calendar' AS k, CAST((SELECT COUNT(*) FROM calendar) AS TEXT) AS v
UNION ALL SELECT 14 AS n, 'amount.north' AS k, printf('%.2f', (SELECT SUM(amount) FROM sales WHERE region = 'north')) AS v
UNION ALL SELECT 15 AS n, 'amount.south' AS k, printf('%.2f', (SELECT SUM(amount) FROM sales WHERE region = 'south')) AS v
UNION ALL SELECT 16 AS n, 'amount.east' AS k, printf('%.2f', (SELECT SUM(amount) FROM sales WHERE region = 'east')) AS v
UNION ALL SELECT 17 AS n, 'amount.west' AS k, printf('%.2f', (SELECT SUM(amount) FROM sales WHERE region = 'west')) AS v
UNION ALL SELECT 18 AS n, 'amount.all' AS k, printf('%.2f', (SELECT SUM(amount) FROM sales)) AS v
UNION ALL SELECT 19 AS n, 'units.all' AS k, CAST((SELECT SUM(units) FROM sales) AS TEXT) AS v
UNION ALL SELECT 20 AS n, 'items.amount.all' AS k, printf('%.2f', (SELECT SUM(amount) FROM sales_items)) AS v
UNION ALL SELECT 21 AS n, 'target.all' AS k, printf('%.2f', (SELECT SUM(target) FROM targets)) AS v
UNION ALL SELECT 22 AS n, 'targets.met' AS k, CAST((SELECT COUNT(*) FROM targets AS t JOIN (SELECT region, SUM(amount) AS amount FROM sales GROUP BY region) AS s ON s.region = t.region WHERE s.amount >= t.target) AS TEXT) AS v
UNION ALL SELECT 23 AS n, 'sales.month.2026-01' AS k, CAST((SELECT COUNT(*) FROM sales AS s JOIN calendar AS c ON c.day = s.day WHERE c.monthName = '2026-01') AS TEXT) AS v
UNION ALL SELECT 24 AS n, 'sales.month.2026-02' AS k, CAST((SELECT COUNT(*) FROM sales AS s JOIN calendar AS c ON c.day = s.day WHERE c.monthName = '2026-02') AS TEXT) AS v
UNION ALL SELECT 25 AS n, 'sales.month.2026-03' AS k, CAST((SELECT COUNT(*) FROM sales AS s JOIN calendar AS c ON c.day = s.day WHERE c.monthName = '2026-03') AS TEXT) AS v
UNION ALL SELECT 26 AS n, 'srSales.all' AS k, printf('%.2f', (SELECT SUM(srSales) FROM sales_report)) AS v
UNION ALL SELECT 27 AS n, 'null.repScore' AS k, CAST((SELECT COUNT(*) FROM dim_rep WHERE repScore IS NULL) AS TEXT) AS v
) AS x ORDER BY n;
