-- GENERATED by data/schema/build-sales-schema.mjs -- do not edit.
-- ErmineSales smoke, mssql. Prints k|v lines; at tier xs the output must equal
-- data/schema/sales.smoke.expected-xs.txt byte for byte.
-- Run: scripts/db.sh sql ErmineSales -i data/schema/sales.smoke.sql -h -1 -W -s '|' -b | sed '/^$/d'
--   (go-sqlcmd appends one empty line after the result set; the sed drops it. MEASURED 2026-09-24.)
SET NOCOUNT ON;
SELECT k, v FROM (
SELECT 1 AS n, 'count.dim_region' AS k, CAST((SELECT COUNT(*) FROM dbo.dim_region) AS varchar(40)) AS v
UNION ALL SELECT 2 AS n, 'count.dim_product' AS k, CAST((SELECT COUNT(*) FROM dbo.dim_product) AS varchar(40)) AS v
UNION ALL SELECT 3 AS n, 'count.dim_channel' AS k, CAST((SELECT COUNT(*) FROM dbo.dim_channel) AS varchar(40)) AS v
UNION ALL SELECT 4 AS n, 'count.dim_rep' AS k, CAST((SELECT COUNT(*) FROM dbo.dim_rep) AS varchar(40)) AS v
UNION ALL SELECT 5 AS n, 'count.dim_customer' AS k, CAST((SELECT COUNT(*) FROM dbo.dim_customer) AS varchar(40)) AS v
UNION ALL SELECT 6 AS n, 'count.dim_date' AS k, CAST((SELECT COUNT(*) FROM dbo.dim_date) AS varchar(40)) AS v
UNION ALL SELECT 7 AS n, 'count.fact_order_line' AS k, CAST((SELECT COUNT(*) FROM dbo.fact_order_line) AS varchar(40)) AS v
UNION ALL SELECT 8 AS n, 'count.fact_target' AS k, CAST((SELECT COUNT(*) FROM dbo.fact_target) AS varchar(40)) AS v
UNION ALL SELECT 9 AS n, 'count.sales_report' AS k, CAST((SELECT COUNT(*) FROM dbo.sales_report) AS varchar(40)) AS v
UNION ALL SELECT 10 AS n, 'count.sales' AS k, CAST((SELECT COUNT(*) FROM dbo.sales) AS varchar(40)) AS v
UNION ALL SELECT 11 AS n, 'count.sales_items' AS k, CAST((SELECT COUNT(*) FROM dbo.sales_items) AS varchar(40)) AS v
UNION ALL SELECT 12 AS n, 'count.targets' AS k, CAST((SELECT COUNT(*) FROM dbo.targets) AS varchar(40)) AS v
UNION ALL SELECT 13 AS n, 'count.calendar' AS k, CAST((SELECT COUNT(*) FROM dbo.calendar) AS varchar(40)) AS v
UNION ALL SELECT 14 AS n, 'amount.north' AS k, CAST(CAST((SELECT SUM(amount) FROM dbo.sales WHERE region = 'north') AS decimal(18,2)) AS varchar(40)) AS v
UNION ALL SELECT 15 AS n, 'amount.south' AS k, CAST(CAST((SELECT SUM(amount) FROM dbo.sales WHERE region = 'south') AS decimal(18,2)) AS varchar(40)) AS v
UNION ALL SELECT 16 AS n, 'amount.east' AS k, CAST(CAST((SELECT SUM(amount) FROM dbo.sales WHERE region = 'east') AS decimal(18,2)) AS varchar(40)) AS v
UNION ALL SELECT 17 AS n, 'amount.west' AS k, CAST(CAST((SELECT SUM(amount) FROM dbo.sales WHERE region = 'west') AS decimal(18,2)) AS varchar(40)) AS v
UNION ALL SELECT 18 AS n, 'amount.all' AS k, CAST(CAST((SELECT SUM(amount) FROM dbo.sales) AS decimal(18,2)) AS varchar(40)) AS v
UNION ALL SELECT 19 AS n, 'units.all' AS k, CAST((SELECT SUM(units) FROM dbo.sales) AS varchar(40)) AS v
UNION ALL SELECT 20 AS n, 'items.amount.all' AS k, CAST(CAST((SELECT SUM(amount) FROM dbo.sales_items) AS decimal(18,2)) AS varchar(40)) AS v
UNION ALL SELECT 21 AS n, 'target.all' AS k, CAST(CAST((SELECT SUM(target) FROM dbo.targets) AS decimal(18,2)) AS varchar(40)) AS v
UNION ALL SELECT 22 AS n, 'targets.met' AS k, CAST((SELECT COUNT(*) FROM dbo.targets AS t JOIN (SELECT region, SUM(amount) AS amount FROM dbo.sales GROUP BY region) AS s ON s.region = t.region WHERE s.amount >= t.target) AS varchar(40)) AS v
UNION ALL SELECT 23 AS n, 'sales.month.2026-01' AS k, CAST((SELECT COUNT(*) FROM dbo.sales AS s JOIN dbo.calendar AS c ON c.day = s.day WHERE c.monthName = '2026-01') AS varchar(40)) AS v
UNION ALL SELECT 24 AS n, 'sales.month.2026-02' AS k, CAST((SELECT COUNT(*) FROM dbo.sales AS s JOIN dbo.calendar AS c ON c.day = s.day WHERE c.monthName = '2026-02') AS varchar(40)) AS v
UNION ALL SELECT 25 AS n, 'sales.month.2026-03' AS k, CAST((SELECT COUNT(*) FROM dbo.sales AS s JOIN dbo.calendar AS c ON c.day = s.day WHERE c.monthName = '2026-03') AS varchar(40)) AS v
UNION ALL SELECT 26 AS n, 'srSales.all' AS k, CAST(CAST((SELECT SUM(srSales) FROM dbo.sales_report) AS decimal(18,2)) AS varchar(40)) AS v
UNION ALL SELECT 27 AS n, 'null.repScore' AS k, CAST((SELECT COUNT(*) FROM dbo.dim_rep WHERE repScore IS NULL) AS varchar(40)) AS v
) AS x ORDER BY n;
